const INIT_REQUEST = 'app/twitter/INIT_REQUEST';
const INIT_SUCCESS = 'app/twitter/INIT_SUCCESS';
const INIT_FAILURE = 'app/twitter/INIT_FAILURE';
const LOGIN_SUCCESS = 'app/twitter/LOGIN_SUCCESS';
const LOGIN_FAILURE = 'app/twitter/LOGIN_FAILURE';
const LOGOUT_REQUEST = 'app/twitter/LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'app/twitter/LOGOUT_SUCCESS';
const LOGOUT_FAILURE = 'app/twitter/LOGOUT_FAILURE';
const GET_TWITTER_REQUEST = 'app/twitter/GET_TWITTER_REQUEST';
const GET_TWITTER_SUCCESS = 'app/twitter/GET_TWITTER_SUCCESS';
const GET_TWITTER_FAILURE = 'app/twitter/GET_TWITTER_FAILURE';

export default {
    INIT_REQUEST,
    INIT_SUCCESS,
    INIT_FAILURE,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT_REQUEST,
    LOGOUT_SUCCESS,
    LOGOUT_FAILURE,
    GET_TWITTER_REQUEST,
    GET_TWITTER_SUCCESS,
    GET_TWITTER_FAILURE,
};
